apiVersion: apps/v1
kind: StatefulSet
metadata:
  name: web
spec:
  serviceName: "app-python"
  replicas: 2
  selector:
    matchLabels:
      app: app-python
  template:
    metadata:
      labels:
        app: app-python
    spec:
      containers:
      - name: app-python
        image: easeln/dockerhub:app_python_v01
        ports:
        - containerPort: 80
          name: web
        volumeMounts:
        - name: www
          mountPath: /
