version: '3.8'

services:

  app_python:
    container_name: monitoring.app_python
    image: aldeeyar/lab2:latest
    mem_limit: 200m
    ports:
      - "80:8000"
    logging:
      driver: "json-file"
      options:
        max-size: "100m"
        max-file: "10"
        tag: "{{.ImageName}}|{{.Name}}"

  loki:
    container_name: monitoring.loki
    image: grafana/loki:2.6.1
    mem_limit: 200m
    expose:
      - 3100
    ports:
      - "3100:3100"
    command: -config.file=/etc/loki/local-config.yaml
    logging:
      driver: "json-file"
      options:
        max-size: "100m"
        max-file: "10"
        tag: "{{.ImageName}}|{{.Name}}"

  promtail:
    container_name: monitoring.promtail
    image: grafana/promtail:2.6.1
    mem_limit: 200m
    expose:
      - 9080
    ports:
      - "9080:9080"
    volumes:
      - ./promtail.yaml:/etc/promtail/promtail.yaml
    command: -config.file=/etc/promtail/promtail.yaml
    labels:
      org.label-schema.group: "monitoring"
    logging:
      driver: "json-file"
      options:
        max-size: "100m"
        max-file: "10"
        tag: "{{.ImageName}}|{{.Name}}"

  grafana:
    container_name: monitoring.grafana
    image: grafana/grafana:latest
    mem_limit: 200m
    volumes:
      - ${PWD}/datasources/loki.yml:/etc/grafana/provisioning/datasources/loki_ds.yml
      - ${PWD}/datasources/prometheus.yml:/etc/grafana/provisioning/datasources/prometheus_ds.yml
    environment:
      - GF_SECURITY_ADMIN_USER=${ADMIN_USER:-admin}
      - GF_SECURITY_ADMIN_PASSWORD=${ADMIN_PASSWORD:-admin}
      - GF_PATHS_PROVISIONING=/etc/grafana/provisioning
    expose:
      - 3000
    ports:
      - "3000:3000"
    logging:
      driver: "json-file"
      options:
        max-size: "100m"
        max-file: "10"
        tag: "{{.ImageName}}|{{.Name}}"
        
  prometheus:
    image: prom/prometheus:latest
    container_name: prometheus
    restart: unless-stopped
    volumes:
      - ./prometheus.yml:/etc/prometheus/prometheus.yml
    command:
      - '--config.file=/etc/prometheus/prometheus.yml'
    expose:
      - 9090
    ports:
      - "9090:9090"
    logging:
      driver: "json-file"
      options:
        max-size: "100m"
        max-file: "10"
        tag: "{{.ImageName}}|{{.Name}}"

volumes:
  promtail-data: {}
