password: ENC[AES256_GCM,data:gzAMhyHvqrPoKf5k8vPu/x0WCjBwtPD9K7/y74qaBgXmsQUuaLzNrC+FN+dH9A==,iv:A6SYWQDnvNOuo/Iw6E+G8kO1lTC9PwdfcZo94NgSSz0=,tag:oAQzQ9OF4AnRsdNvaAcmZA==,type:str]
example_key: ENC[AES256_GCM,data:tx0iUE4qvigu8DLVzQ==,iv:ZDERTi3GH0gBaHVicFuLEv4J2+bgeF4cNQlmAL5kD28=,tag:IMwipDznUfshZfuKCcEj7Q==,type:str]
#ENC[AES256_GCM,data:2zjc6UV1hdnvezZb3js4Ng==,iv:9w90ewwUFI/Cngbckp5nuQxN4fofADARbtVpVWL9xSQ=,tag:v8qRtDtPGfO+gdVekIta6g==,type:comment]
example_array:
    - ENC[AES256_GCM,data:r+cEQ8Pk/YsPS+W3CCU=,iv:hHGuYxtoL1eoxckUN9aQOP6X6CeFdAknuAh5jMPbQCM=,tag:42MSzOBWbWyJCjFXF6/ZlA==,type:str]
    - ENC[AES256_GCM,data:TPXFuIX7IL8YiHL/2TA=,iv:hZHD3ezNFI/5d5HVsXqtk+uyUDAPLF28EdKXyflE+PI=,tag:0TjZsGX7nJG4DR8UbRwapw==,type:str]
example_number: ENC[AES256_GCM,data:V0+dL5dDMiqyHQ==,iv:bfiTbDJ9ng3ydej4HXXue7iUNI1ASEkCM3baS6rWhKU=,tag:A30zL1NYSDYiCklOFoP4wA==,type:float]
example_booleans:
    - ENC[AES256_GCM,data:HxZRJA==,iv:CQZeN7hAFTWQCrMpsYs1DIjUwidqcvbphF1IN7RHIxQ=,tag:XVRXe5pEApsYIbD0CxEKFw==,type:bool]
    - ENC[AES256_GCM,data:ptxW2G8=,iv:mMrtSJmZeSM7SYwOO0PbBV5C4tfBVfwUhfKJCtDHnIk=,tag:nLdV5E9tlLKBe5uJZS8bdg==,type:bool]
sops:
    kms: []
    gcp_kms: []
    azure_kv: []
    hc_vault: []
    age: []
    lastmodified: "2022-11-15T09:42:49Z"
    mac: ENC[AES256_GCM,data:hrSS0VAvodxUvhefmxG33NbhzoLdaGHOZRf5qb5EWemTrYl2GIiZZbd8U+InSRa19+EBtr++2QYlly6kChIk2rYMljl/Dlnb1RCbWEHbjXleeJLDqvHmooEDub/epfraTr+UtYF5ulXYj7O57UIel/xqw3GNXQQbAK0ZD0XJIbo=,iv:lYkoA2p0FhVdk9fPmOtbSrT5Ayh4OMUpr/aCobndtc8=,tag:A8lLh0b5Q9Yd42YMQYN3Rg==,type:str]
    pgp:
        - created_at: "2022-11-15T09:42:07Z"
          enc: |
            -----BEGIN PGP MESSAGE-----

            hQGMA/9z5ACJTvhOAQv/RRx3dtJli6Zte4Hnm+khigVFuW/ew/n+CEyRW9Bu9KnU
            Z9DY9oPzEGDsmAuNjwE2Zn2x+uGRtHmPCyz1uVuBSzUelZR7z+/Sh1dxzopGdNnc
            RM6KRpi5wlRBF+Nz54jLMPMLvcbVDf/b9o6PCWKRdLjO5/cn1nv7OGEUQO2yQ0kZ
            fRfBZLn5NuFz2oEXissRg0BLla/ppp63V9273Tbw9n6V+6ODtFq+roVtWeuR6zuk
            So3Agss+yueRhJOJqUD71JeDeXR6Pj3Sm7aB7jqkpxDJ7MSUKnO9JzAgYoJfYp13
            sFap8dxwduksywNpopkrl1cwtLA1cXQj+osliSKOKsnPEYh2ptHrTM245NlYjJ6Q
            LAWoVKWe8SXU20D7CfsjumSL/Ekl6rI6XEijJvfNKlVioNHjmseRkSDLKZOmZUM3
            Z4E337KKRnqQUNsOsqyyfVXiP51EkrDKixGkpr0YfIW3yuClhqB4XMEwX/15be5I
            WWUI2BoINseceHRQZtZW0lwBzisSXPEyQLMCZyaD+6OJ55zfl6iRLtRkuFHwLibY
            m5PpdukBk/brNlgZpsUmmdfWJEvkqhCMTRs9K4t+T8XFrlqCsVLzQxi7jZ6du8t2
            5aDa77PC3hJeXCwDeA==
            =e58b
            -----END PGP MESSAGE-----
          fp: 9328CB4E8DD414481156EB07B07F3B85527721A2
    unencrypted_suffix: _unencrypted
    version: 3.7.3
